name: Collect Game Ads

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày lúc nửa đêm
  workflow_dispatch:      # Cho phép chạy thủ công khi cần

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run ad collection script
        run: python scripts/collect_ads.py
        
      - name: Run analysis script
        run: python scripts/analyze_ads.py
        
      - name: Update website data
        run: python scripts/update_website.py
        
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/
          git commit -m "Auto-update ads data" || exit 0
          git push
